#!/home/chiba/.npm-global/bin/spang2
# @endpoint https://orth.dbcls.jp/sparql-plant
# @param queryGene=815275
# @param targetTaxon=3847
# @option -a

PREFIX taxid: <http://identifiers.org/taxonomy/>
PREFIX ncbigene: <http://identifiers.org/ncbigene/>
PREFIX plant: <https://plant-oms.dbcls.jp/ontology#>

SELECT ?gene ?score
WHERE {
  ?hit plant:queryGene ncbigene:${queryGene} ;
       plant:targetTaxon taxid:${targetTaxon} ;
       plant:targetGene ?gene ;
       plant:score ?score .
}
ORDER BY DESC(?score)
